# ICO Data object example

In [1]:
import ICO
import os
import pandas as pd
import time

The `Data` object is initialized with the path to the directory of .pickle files. On creation it reads in the pickle files, but does not transform the data.

In [2]:
data = ICO.Data(os.getcwd()+'/data/')

The `data` object can be accessed like a dictionary to the underlying `Dataframes`. These will be transformed on their first access into a normalized form. (This might take awhile for the first access)

In [3]:
start = time.time()
data["all_encounter_data"]
print(time.time() - start)

ICO.py:108: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  dEI[diagnosis]=dEI["Diagnosis_Code_ID"].str.contains(pattern)

68.5258469582

In [4]:
data["all_encounter_data"].describe(include='all')

,Enc_Date,Person_Nbr,Primary_Payer,Smoking_Status,MR_OD_SPH,MR_OD_CYL,MR_OD_AXIS,MR_OD_DVA,MR_OD_NVA,MR_OS_SPH,...,ME,MNPDR,DM,SNPDR,Glaucoma_Suspect,mNPDR,Open_angle_Glaucoma,PDR,Cataract,DR_diagnosis
count,61862,6.186200e+04,61862,57359,24558,23803,19179,23300,17456,24541,...,61862,61862,61862,61862,61862,61862,61862,61862,61862,61862
unique,51745,NaN,86,9,190,66,249,290,219,194,...,2,2,2,2,2,2,2,2,2,5
top,2016-05-23 06:15:00,NaN,Medicare,Never smoker,PL,Sph,090,20/20,20/20,PL,...,False,False,False,False,False,False,False,False,False,no_DR
freq,5,NaN,23199,30865,2283,4597,2674,12685,11384,2283,...,59054,59850,32358,60955,51093,57307,52221,58186,45829,51311
first,2011-10-28 23:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
last,2016-11-03 23:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,5.231971e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,3.011000e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,3.300000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,2.626995e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,5.159770e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,7.823740e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,1.048528e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
start = time.time()
data["all_person_data"]
print(time.time() - start)

55.8759520054

In [6]:
data["all_person_data"].describe(include='all')

,DOB,Gender,Race,A1C,BMI,Glucose,BP_Systolic,BP_Diastolic,Last_Encounter,DM,...,MNPDR,PDR,SNPDR,mNPDR,Glaucoma_Suspect,Open_angle_Glaucoma,Cataract,worst_DR,recent_DR,Age
count,16039,16039,16039,4708.000000,6473.000000,10178.000000,14358.000000,14374.000000,16039,16039,...,16039,16039,16039,16039,16039,16039,16039,16039,16039,16039.000000
unique,10735,3,10,NaN,NaN,NaN,NaN,NaN,15051,2,...,2,2,2,2,2,2,2,5,5,NaN
top,1961-03-18 00:00:00,F,Black or African American,NaN,NaN,NaN,NaN,NaN,2016-04-21 15:15:00,True,...,False,False,False,False,False,False,False,no_DR,no_DR,NaN
freq,7,10236,9780,NaN,NaN,NaN,NaN,NaN,4,13321,...,15099,14999,15689,13421,12439,14554,9170,12009,12009,NaN
first,1901-01-06 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011-10-31 15:30:00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
last,1998-03-23 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-11-03 23:15:00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,7.235485,31.867714,131.677803,133.611368,78.109281,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.390423
std,NaN,NaN,NaN,1.241573,6.785681,32.121431,17.023775,10.384908,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.806935
min,NaN,NaN,NaN,3.900000,14.395000,40.000000,87.000000,48.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.000000
25%,NaN,NaN,NaN,6.300000,26.880000,109.500000,122.000000,70.675000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.000000
50%,NaN,NaN,NaN,7.000000,31.170000,127.000000,132.000000,78.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.000000
75%,NaN,NaN,NaN,8.000000,36.120000,150.000000,144.000000,85.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71.000000
max,NaN,NaN,NaN,10.600000,50.580000,222.000000,181.000000,107.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,114.000000

In [8]:
quantitive_columns=['A1C', 'BMI', 'Glucose', 'BP_Diastolic', 'BP_Systolic']
data['all_person_data'][quantitive_columns].isnull().sum(axis=0)/data['all_person_data'].shape[0]

A1C             0.706465
BMI             0.596421
Glucose         0.365422
BP_Diastolic    0.103809
BP_Systolic     0.104807
dtype: float64

In [9]:
data['all_encounter_data'].to_pickle('all_encounter_data_Dan_20170329.pickle')

In [10]:
data['all_person_data'].to_pickle('all_person_data_Dan_20170329.pickle')